create table public.user_anime (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null,
  name text not null,
  name_cn text,
  image_url text,
  total_episodes integer,
  community_score numeric(3,1),
  status text not null check (status in ('wish','watching','done','paused','dropped')) default 'wish',
  progress integer not null default 0 check (progress >= 0),
  rating integer not null default 0 check (rating between 0 and 10),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, anime_id)
);
alter table public.user_anime enable row level security;
create policy "Users can read own anime" on public.user_anime for select using (auth.uid() = user_id);
create policy "Users can insert own anime" on public.user_anime for insert with check (auth.uid() = user_id);
create policy "Users can update own anime" on public.user_anime for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own anime" on public.user_anime for delete using (auth.uid() = user_id);
