-- 尚文番迹数据库初始化 / 升级脚本（可重复运行）
create table if not exists public.anime_collections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 30),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, name)
);

-- 好友功能：公开资料只用于好友界面；邮箱查找通过受控函数完成。
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  avatar_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id),
  unique(requester_id, addressee_id)
);

create table if not exists public.user_anime (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null,
  name text not null,
  name_cn text,
  image_url text,
  total_episodes integer,
  community_score numeric(3,1),
  status text not null check (status in ('wish','watching','done','paused','dropped')) default 'wish',
  progress integer not null default 0 check (progress >= 0),
  rating integer not null default 0 check (rating between 0 and 10),
  note text,
  collection_id bigint references public.anime_collections(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, anime_id)
);

-- 为已经存在的旧表补上收藏夹字段。
alter table public.user_anime
  add column if not exists collection_id bigint references public.anime_collections(id) on delete set null;

alter table public.user_anime enable row level security;
alter table public.anime_collections enable row level security;
alter table public.profiles enable row level security;
alter table public.friendships enable row level security;

drop policy if exists "Users can read own anime" on public.user_anime;
drop policy if exists "Users can insert own anime" on public.user_anime;
drop policy if exists "Users can update own anime" on public.user_anime;
drop policy if exists "Users can delete own anime" on public.user_anime;
create policy "Users can read own anime" on public.user_anime for select using (auth.uid() = user_id);
create policy "Users can insert own anime" on public.user_anime for insert with check (auth.uid() = user_id);
create policy "Users can update own anime" on public.user_anime for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own anime" on public.user_anime for delete using (auth.uid() = user_id);

drop policy if exists "Users can read own collections" on public.anime_collections;
drop policy if exists "Users can insert own collections" on public.anime_collections;
drop policy if exists "Users can update own collections" on public.anime_collections;
drop policy if exists "Users can delete own collections" on public.anime_collections;
create policy "Users can read own collections" on public.anime_collections for select using (auth.uid() = user_id);
create policy "Users can insert own collections" on public.anime_collections for insert with check (auth.uid() = user_id);
create policy "Users can update own collections" on public.anime_collections for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own collections" on public.anime_collections for delete using (auth.uid() = user_id);

-- 已成为好友后，双方可只读查看彼此的“看完”记录及收藏夹。
drop policy if exists "Friends can read completed anime" on public.user_anime;
create policy "Friends can read completed anime" on public.user_anime for select using (
  status = 'done' and exists (
    select 1 from public.friendships f where f.status = 'accepted' and
    ((f.requester_id = auth.uid() and f.addressee_id = user_id) or
     (f.addressee_id = auth.uid() and f.requester_id = user_id))
  )
);
drop policy if exists "Friends can read collections" on public.anime_collections;
create policy "Friends can read collections" on public.anime_collections for select using (
  exists (
    select 1 from public.friendships f where f.status = 'accepted' and
    ((f.requester_id = auth.uid() and f.addressee_id = user_id) or
     (f.addressee_id = auth.uid() and f.requester_id = user_id))
  )
);

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles" on public.profiles for select to authenticated using (
  id = auth.uid() or exists (
    select 1 from public.friendships f where
    (f.requester_id = auth.uid() and f.addressee_id = profiles.id) or
    (f.addressee_id = auth.uid() and f.requester_id = profiles.id)
  )
);
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Users can read related friendships" on public.friendships;
drop policy if exists "Users can create friend requests" on public.friendships;
drop policy if exists "Addressee can update friend requests" on public.friendships;
drop policy if exists "Users can delete related friendships" on public.friendships;
create policy "Users can read related friendships" on public.friendships for select using (auth.uid() in (requester_id, addressee_id));
create policy "Users can create friend requests" on public.friendships for insert with check (auth.uid() = requester_id and status = 'pending');
create policy "Addressee can update friend requests" on public.friendships for update using (auth.uid() = addressee_id) with check (auth.uid() = addressee_id);
create policy "Users can delete related friendships" on public.friendships for delete using (auth.uid() in (requester_id, addressee_id));

create or replace function public.handle_new_user_profile()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,email,display_name,avatar_url)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1)),new.raw_user_meta_data->>'avatar_url')
  on conflict(id) do update set email=excluded.email, display_name=coalesce(excluded.display_name,profiles.display_name), avatar_url=coalesce(excluded.avatar_url,profiles.avatar_url), updated_at=now();
  return new;
end; $$;
drop trigger if exists on_auth_user_profile_changed on auth.users;
create trigger on_auth_user_profile_changed after insert or update of email,raw_user_meta_data on auth.users
for each row execute function public.handle_new_user_profile();

-- 给已有账号补公开资料。
insert into public.profiles(id,email,display_name,avatar_url)
select id,email,coalesce(raw_user_meta_data->>'display_name',split_part(email,'@',1)),raw_user_meta_data->>'avatar_url' from auth.users
on conflict(id) do nothing;

create or replace function public.send_friend_request(target_email text)
returns bigint language plpgsql security definer set search_path = public as $$
declare caller_id uuid := auth.uid(); target_id uuid; request_id bigint;
begin
  if caller_id is null then raise exception '登录状态已失效，请退出后重新登录'; end if;
  select id into target_id from auth.users where lower(email)=lower(trim(target_email));
  if target_id is null then raise exception '没有找到这个邮箱的用户'; end if;
  if target_id = caller_id then raise exception '不能添加自己'; end if;
  insert into public.profiles(id,email,display_name,avatar_url)
  select id,email,coalesce(raw_user_meta_data->>'display_name',split_part(email,'@',1)),raw_user_meta_data->>'avatar_url'
  from auth.users where id in (caller_id,target_id)
  on conflict(id) do update set email=excluded.email,display_name=coalesce(profiles.display_name,excluded.display_name),avatar_url=coalesce(profiles.avatar_url,excluded.avatar_url),updated_at=now();
  if exists(select 1 from public.friendships where status='accepted' and ((requester_id=caller_id and addressee_id=target_id) or (requester_id=target_id and addressee_id=caller_id))) then raise exception '你们已经是好友'; end if;
  if exists(select 1 from public.friendships where status='pending' and requester_id=target_id and addressee_id=caller_id) then raise exception '对方已经向你发送申请，请到收到的申请中同意'; end if;
  insert into public.friendships(requester_id,addressee_id,status) values(caller_id,target_id,'pending')
  on conflict(requester_id,addressee_id) do update set status='pending',updated_at=now()
  returning id into request_id;
  return request_id;
end; $$;
revoke all on function public.send_friend_request(text) from public, anon;
grant execute on function public.send_friend_request(text) to authenticated;
