-- 尚文番迹数据库初始化 / 升级脚本（可重复运行）
create table if not exists public.anime_collections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 30),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, name)
);

create table if not exists public.user_anime (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null,
  name text not null,
  name_cn text,
  image_url text,
  total_episodes integer,
  community_score numeric(3,1),
  status text not null check (status in ('wish','watching','done','paused','dropped')) default 'wish',
  progress integer not null default 0 check (progress >= 0),
  rating integer not null default 0 check (rating between 0 and 10),
  note text,
  collection_id bigint references public.anime_collections(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, anime_id)
);

-- 为已经存在的旧表补上收藏夹字段。
alter table public.user_anime
  add column if not exists collection_id bigint references public.anime_collections(id) on delete set null;

alter table public.user_anime enable row level security;
alter table public.anime_collections enable row level security;

drop policy if exists "Users can read own anime" on public.user_anime;
drop policy if exists "Users can insert own anime" on public.user_anime;
drop policy if exists "Users can update own anime" on public.user_anime;
drop policy if exists "Users can delete own anime" on public.user_anime;
create policy "Users can read own anime" on public.user_anime for select using (auth.uid() = user_id);
create policy "Users can insert own anime" on public.user_anime for insert with check (auth.uid() = user_id);
create policy "Users can update own anime" on public.user_anime for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own anime" on public.user_anime for delete using (auth.uid() = user_id);

drop policy if exists "Users can read own collections" on public.anime_collections;
drop policy if exists "Users can insert own collections" on public.anime_collections;
drop policy if exists "Users can update own collections" on public.anime_collections;
drop policy if exists "Users can delete own collections" on public.anime_collections;
create policy "Users can read own collections" on public.anime_collections for select using (auth.uid() = user_id);
create policy "Users can insert own collections" on public.anime_collections for insert with check (auth.uid() = user_id);
create policy "Users can update own collections" on public.anime_collections for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own collections" on public.anime_collections for delete using (auth.uid() = user_id);
